version: "3.9"
services:
  nginx:
    image: nginx:latest
    deploy:
      replicas: 1
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/nginx.conf
    ports:
      - 4567:4567
  webapp:
    build:
      context: .
    deploy:
      replicas: 1
    working_dir: /usr/src/app
    volumes:
      - "./python_code:/usr/src/app"
      - "./auth-vals.json:/usr/src/app/auth-vals.json"
    entrypoint: [ "python3", "server.py", "8080"] 
configs:
  nginx_conf:
    file: ./nginx.conf

